/* SoC level DTS fixup file */

#define DT_ARM_GIC_NAME		DT_ARM_GIC_D1D81000_LABEL
#define DT_GIC_DIST_BASE	DT_ARM_GIC_D1D81000_BASE_ADDRESS_0
#define DT_GIC_CPU_BASE		DT_ARM_GIC_D1D81000_BASE_ADDRESS_1
#define CONFIG_GIC_ISR_TBL_OFFSET	CONFIG_2ND_LVL_ISR_TBL_OFFSET

/* End of SoC Level DTS fixup file */
